name: Unit test pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Getting code source
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependecies
        run: npm ci
      - name: Run tests
        run: npm test